- name: Set Breadth Route
  vars:
    fqdn_services_breadth_route: "{{all_services | map(attribute='fqdn') | select('search', 'breadth') | list | difference(all_services | map(attribute='fqdn') | select('search', 'breadth-sink') | list) }}"
  set_fact:
    full_route: "http://{{fqdn_services_breadth_route[0]}}/route?path={{item}};{{ full_route }}"
    kiali_test_breadth_namespace: "{{all_services | map(attribute='namespace') | select('search', 'breadth') | list | first }}"
  with_items:
  - "{{ fqdn_services_breadth_route | reverse | list  }}"
