FROM quay.io/centos/centos:8

LABEL maintainer="kiali-dev@googlegroups.com"

ENV CLIENT_HOME=/opt/client \
    PATH=$CLIENT_HOME:$PATH

WORKDIR $CLIENT_HOME

COPY client-${TARGETARCH} $CLIENT_HOME/client

ENTRYPOINT ["/opt/client/client"]
