apiVersion: v1
kind: Service
metadata:
  namespace: "{{ item.namespace }}"
  name: "{{ item.name }}"
  labels:
    kialiScaleMesh: "true"
    app: {{ item.app }}
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8888
  selector:
    app: {{ item.app }}
