apiVersion: v1
kind: Service
metadata:
  namespace: "{{ item.namespace }}"
  name: "{{ item.name }}"
  labels:
    kialiScaleMesh: "true"
    app: {{ item.app }}
{% if custom_labels_map | length > 0 %}
    {{ custom_labels_map | to_nice_yaml(indent=0) | trim | indent(4) }}
{% endif %}
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8888
  selector:
    app: {{ item.app }}
