apiVersion: maistra.io/v1
kind: ServiceMeshMember
metadata:
  namespace: "{{ item }}"
  name: "default"
  labels:
    kialiScaleMesh: "true"
spec:
  controlPlaneRef:
    name: "{{ control_plane_namespace }}"
    namespace: "{{ control_plane_namespace }}"
