apiVersion: maistra.io/v1
kind: ServiceMeshMember
metadata:
  namespace: "{{ item }}"
  name: "default"
  labels:
    kialiScaleMesh: "true"
spec:
  controlPlaneRef:
    name: "{{ maistra_smcp.metadata.name }}"
    namespace: "{{ maistra_smcp.metadata.namespace }}"
