apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-v2
spec:
  selector:
    matchLabels:
      app: bookstore
      version: v2
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: bookstore
        version: v2
    spec:
      containers:
        - name: bookstore
          image: kiali/demo_error_rates_server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: CODE_REQUESTS
              value: "200,8;201,1;202,1"
            - name: SERVER_NAME
              value: "bookstore-v2"
            - name: SERVER_URL
              value: "http://www.bookdepository.com"